# Generated by Django 4.2.27 on 2026-01-12 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('spam', 'Спам'), ('inappropriate_content', 'Неуместный контент'), ('fraud', 'Мошенничество'), ('harassment', 'Домогательство'), ('other', 'Другое')], max_length=50, verbose_name='Тип жалобы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('reviewed', 'Рассмотрена'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('moderator_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Жалобщик')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('reported_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='activities.request', verbose_name='На какую заявку пожаловались')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_against', to=settings.AUTH_USER_MODEL, verbose_name='На кого пожаловались')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_type', models.CharField(choices=[('temporary', 'Временная'), ('permanent', 'Постоянная')], max_length=20, verbose_name='Тип блокировки')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('starts_at', models.DateTimeField(verbose_name='Начало блокировки')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец блокировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Блокировка',
                'verbose_name_plural': 'Блокировки',
                'ordering': ['-created_at'],
            },
        ),
    ]
